name: DOCOLOOP edit
description: Submit a doco edit.
title: "[docoloop-edit]: "
labels: ["docoloop", "edit"]
projects: ["docoloop-edit/1"]
assignees:
  - docoloop, edit
body:
  - type: markdown
    attributes:
      value: ""## Welcome to DOCOLOOP"
    attributes:
      value: |
        Thanks for taking the time to help improve our doco!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-needs-editing
    attributes:
      label: edit-type
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "This needs an edit!"
    validations:
      required: true
  - type: dropdown
    id: edit-type
    attributes:
      label: type
      description: What type of edit is needed?
      options:
        - spelling
        - context
        - outdated
        - broken link
        - nonsense
        - other
      default: 0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: describe
      description: Please leave other comments or information.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
